# Generated by Django 3.0.6 on 2020-06-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='during_date',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='max_person',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pakage_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pakage_num',
            field=models.IntegerField(default=0, help_text='4자리로 입력해주세요.', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pre_person',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
