# Generated by Django 3.0.6 on 2020-06-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200606_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='during_date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='max_person',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='pakage_name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='pakage_num',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='pre_person',
        ),
    ]
