# Generated by Django 3.0.6 on 2020-06-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200606_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='during_date',
            field=models.CharField(default='입력값없음.', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='max_person',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pakage_name',
            field=models.CharField(default='값없음', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pakage_num',
            field=models.IntegerField(default=0, help_text='4자리로 입력해주세요.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pre_person',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
